version: "3.3"
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: ./akchak-front/Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - app-tier
    volumes:
      - ./akchak-front:/app/akchak-front
      - /app/akchak-front/node_modules

  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: ./akchak-server/Dockerfile
    ports:
      - 5000:5000
      - 9229:9229
    networks:
      - app-tier
    volumes:
      - ./akchak-server:/app/akchak-server
      - /app/akchak-server/node_modules
    restart: unless-stopped

networks:
  app-tier:
    driver: bridge
